@extends('layouts.app')

@section('content')
    <x-common.page-breadcrumb pageTitle="Catat Payment" />

    <x-common.component-card title="Form Payment" desc="Catat payment dan perbarui saldo booking secara otomatis.">
        <form method="POST" action="{{ route('payments.store') }}" class="space-y-6">
            @csrf
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Booking</label><select name="booking_id" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90"><option value="">Pilih booking</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected(request('booking_id') == $booking->id || old('booking_id') == $booking->id)>{{ $booking->booking_code }} - {{ $booking->guest_name }}</option>@endforeach</select>@error('booking_id')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-2"><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Jumlah (Rupiah)</label><input type="number" step="1" min="1" name="amount" value="{{ old('amount') }}" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90" />@error('amount')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Tanggal Payment</label><input type="datetime-local" name="paid_at" value="{{ old('paid_at', now()->format('Y-m-d\TH:i')) }}" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90" />@error('paid_at')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div></div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-2"><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Metode</label><select name="payment_method" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90"><option value="cash" @selected(old('payment_method') === 'cash')>Cash</option><option value="transfer" @selected(old('payment_method') === 'transfer')>Transfer</option></select>@error('payment_method')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Diterima Oleh</label><select name="received_by" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90"><option value="finance" @selected(old('received_by') === 'finance')>Finance</option><option value="office" @selected(old('received_by') === 'office')>Office</option><option value="field_staff" @selected(old('received_by') === 'field_staff')>Field Staff</option></select>@error('received_by')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Path Bukti Payment</label><input type="text" name="proof_image" value="{{ old('proof_image') }}" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90" />@error('proof_image')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Catatan</label><textarea name="note" rows="4" class="w-full rounded-lg border border-gray-300 bg-transparent px-4 py-3 text-sm text-gray-800 shadow-theme-xs dark:border-gray-700 dark:bg-white/[0.03] dark:text-white/90">{{ old('note') }}</textarea>@error('note')<p class="mt-2 text-sm text-error-600 dark:text-error-400">{{ $message }}</p>@enderror</div>
            <div class="flex items-center justify-end gap-3"><a href="{{ route('payments.index') }}" class="rounded-lg border border-gray-300 px-5 py-3 text-sm font-medium text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.03]">Batal</a><button type="submit" class="rounded-lg bg-brand-500 px-5 py-3 text-sm font-medium text-white shadow-theme-xs transition hover:bg-brand-600">Simpan Payment</button></div>
        </form>
    </x-common.component-card>
@endsection

